name: Via Cep API Testing CI

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: Rodar testes
        run: mvn clean test
        continue-on-error: true
      
      - name: Gerar Allure report
        run: mvn allure:report

      - name: Verificar estrutura do report
        run: find target -name "allure-maven.html"

      - name: Criar index.html com redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=allure-maven.html">' > target/site/allure-maven-plugin/index.html

      - name: Gerar Report da Allure no Github Pages
        uses:  peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          destination_dir: .